### ISSUE TITLE
Extraneous Schemas Generated for Models Containing Array Properties 

### ISSUE THREAD

**Issue by leedsalex** [swagger-akka-http/swagger-scala-module#195]
This might be related to #63

Note: We use this package directly, not as part of [swagger-akka-http](https://github.com/swagger-akka-http/swagger-akka-http). We only generate schemas for models, and don't use any annotations.

Given a case class that contains a single property which is a `Seq`, there are two schemas generated, `Foo` and `SeqString`, i'm unsure why the `SeqString` schema is generated as it's not referenced in the `Foo` schema. This appears to be a bug.

```scala
    case class Foo(bar: Seq[String])
    val schema = ModelConverters.getInstance().readAll(classOf[Foo])
    val yaml = Yaml.pretty(schema)
    println(yaml)
```

```yaml
Foo:
  required:
    - bar
  type: object
  properties:
    bar:
      type: array
      items:
        type: string
SeqString:
  type: array
  items:
    type: string
```
