### ISSUE TITLE
Improper or Alternative Handling of Required Properties

### ISSUE THREAD

**Issue by leedsalex** [swagger-akka-http/swagger-scala-module#204]
In the current state, a non-annotated model with a default value, such as:
```scala
case class ModelWithInt(int: Int = 0)
```
will resolve to the following schema:
```yaml
ModelWithInt:
  type: object
  properties:
    int:
      type: integer
      default: 0
```

However, most code generators will interpret this schema as: 
```scala  
case class ModelWithInt(int: Option[Int] = Some(0))
```
In other languages, where `Option` types don't exist, this property would be a pointer or something similar.

I propose that we change the ability to use the `default value` as a determining factor for optionality (i.e marking a property required) a configurable option.
